AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - lib/tasks/*.rake
    - bin/update
    - bin/setup
    - config/environments/*
    - lib/tasks/erb_to_slim.rake
    - db/**/*
    - node_modules/**/*
    - Brewfile
    - Guardfile
    - .pryrc

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
